name: gnews
description: A starting point for Dart libraries or applications.
version: 1.0.2
repository: https://github.com/RizkiePratama/gnews.dart

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  html: ^0.15.3
  http: ^0.13.6
  mockito: ^5.4.1

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.0.0
  test: ^1.21.0
